# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76c1c7572278e4a4cedbe364f1a1c5bc6fc389aedc10e70513d77cf90e51a0b70e9a5b0345553401fc2c1dd61884b21752daa2a1712154bb865d24e07b0de699

test:
  secret_key_base: 9c3d65496c1d2e46f184eb30107ece4f7b21591a0dafa2a2e28a067dc57b40851b92879d45a0b19f2e2d1f19ce78ebd8ca30c9e791e108030ba52cefce0b5e4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
